services:
  postgres:
    image: postgres:16.3
    container_name: dmsdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dmsdb
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: "pg_isready -U postgres"
